BEGIN;

CREATE TABLE IF NOT EXISTS roles
(
    id  serial PRIMARY KEY,
    name VARCHAR UNIQUE  NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

COMMIT;