version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pp_api
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./configs:/app/configs
  db:
    image: "postgres"
    env_file:
      - configs/.env
    volumes:
        - .tmp/db:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://test:password@db:5432/go_sample?sslmode=disable", "up" ]
    depends_on:
      db:
        condition: service_healthy
